# Generated by Django 4.2.3 on 2023-07-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdi', '0002_alter_formation_nbrmatier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='formation',
            name='matiere1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matiere1_formations', to='cdi.matiere'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='matiere2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matiere2_formations', to='cdi.matiere'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='matiere3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matiere3_formations', to='cdi.matiere'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='matiere4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matiere4_formations', to='cdi.matiere'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='matiere5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matiere5_formations', to='cdi.matiere'),
        ),
    ]
