# Generated by Django 4.2.3 on 2023-08-01 11:09

import cdi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi', '0003_alter_formation_description_alter_formation_matiere1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=cdi.models.image_uoload_profile)),
                ('price', models.FloatField()),
                ('pricenet', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
