# Generated by Django 4.2.3 on 2023-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi', '0006_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
